APP_ENV: DEV # DEV,TEST,PROD (DEV and TEST print logs in CMD screen)
LOG_LEVEL: "0"
# panic (zerolog.PanicLevel, 5)
# fatal (zerolog.FatalLevel, 4)
# error (zerolog.ErrorLevel, 3)
# warn (zerolog.WarnLevel, 2)
# info (zerolog.InfoLevel, 1)
# debug (zerolog.DebugLevel, 0)
# trace (zerolog.TraceLevel, -1)
ORCHESTRATORM8:
  Services:
      num8: "http://127.0.0.1:8003"
      asmm8: "http://127.0.0.1:8000"
  Exchanges: # Format below: exchange_name:exchange_type
    cptm8: "topic"
    notification: "topic"
  num8: # API service name
    Queue:
      - "cptm8" # exchange name
      - "qnum8" # queue name
      - 2 # prefetch count
    Routing-keys:
      - "cptm8.num8.#" # binding key
    Queue-arguments:
      "x-max-length": 2 # x-queue-type, x-max-length, x-max-length-bytes, x-overflow, x-message-ttl, x-expires, x-max-age, x-stream-max-segment-size-bytes, x-queue-version, x-consumer-timeout, x-single-active-consumer
      "x-overflow": "reject-publish"
    Consumer:
      - "qnum8" # queue name
      - "cnum8" # consumer name
      - "false" # autoack
    Publisher: # This the default published message
      - "cptm8" # exchange
      - "cptm8.asmm8.get.scan" # Routing key
      - "num8" # caller service
NUM8: # Nuclei scan settins and Burp API and Proxy location
  BurpAPILocation: http://127.0.0.1:8090
  BurpProxyLocation: http://127.0.0.1:8080
  # proxy: socks5://user:pass@IPaddress:Port
  Sitemap:
    Filter:
      StatusCode:
        - "301"
        - "302"
        - "304"
        - "307"
        - "400"
        - "404"
        - "415"
        - "500"
        - "502"
      ContentType:
      - "Content-Type: image/x-icon"
      - "Content-Type: image/bmp"
      - "Content-Type: image/gif"
      - "Content-Type: image/vnd.microsoft.icon"
      - "Content-Type: image/jpeg"
      - "Content-Type: image/png"
      - "Content-Type: image/svg+xml"
      - "Content-Type: image/tiff"
      - "Content-Type: image/webp"
      - "Content-Type: video/mp4"
      - "Content-Type: text/css"
      - "Content-Type: application/x-javascript"
      - "Content-Type: text/javascript"
      - "Content-Type: application/javascript"
      - "Content-Type: application/pdf"
      - "Content-Type: application/x-font-woff"
      - "Content-Type: application/x-font-woff2"
      - "Content-Type: application/font-woff"
      - "Content-Type: font/woff"
      - "Content-Type: font/woff2"
  t:
    - /home/deifzar/nuclei-templates
  turl:
    - https://cloud.projectdiscovery.io/public/
  trustedDomains:
    - 127.0.0.1:8000
    - cloud.projectdiscovery.io
  templateSources:
    - http://127.0.0.1:8000/
    - http://127.0.0.1:8000/ 
Database: # PostgreSQL connection details
  location: "hostname"
  port: 5432
  schema: "public"
  database: "databasename"
  username: "dbuser"
  password: "dbpass"
RabbitMQ: # RabbitMQ connection details
  location: "hostname"
  port: 5672
  username: "user"
  password: "pass"
  pool:
    max_connections: # default: 10
    min_connections: # default: 2
    pool.max_idle_time: # default: "1h" Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
    max_lifetime: # default: "2h" Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
    health_check_period: # default: "30m" Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
    connection_timeout: # default: "30s" Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
    retry_attempts: # default: 3
    retry_delay: # default: "2s" Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".